module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    fontSize: {
      9: "9.6px",
      11: "11px",
      12: "12px",
      14: "14px",
      16: "16px",
      22: "22.4px",
      20: "20px",
      80: "80px",
      82: "82px",
      xs: ".75rem",
      sm: ".875rem",
      tiny: ".875rem",
      base: "1rem",
      lg: "1.125rem",
      xl: "1.25rem",
      "2xl": "1.5rem",
      "3xl": "1.875rem",
      "4xl": "2.25rem",
      "5xl": "3rem",
      "6xl": "4rem",
      "7xl": "5rem",
    },
    letterSpacing: {
      2: "2px",
    },
    extend: {},
    fontFamily: {
      raleway: ["Raleway"],
      graphik: ["Graphik"],
      sourceSansPro: ["Source Sans Pro"],
      robotoCondensed: ["Roboto Condensed"],
      overpassMono: ["Overpass Mono"],
    },
  },
  plugins: [],
};
