export default [
  {
    name: "Clane Website",
    title: "A React Web Application",
    tools: ["React", "Redux", "TailwindCSS", "Styled-Component", "Axios"],
    images: [],
    details: "",
    tag: "web",
  },
  {
    name: "Rapid",
    title: "A React Native Merchant Mobile Application",
    tools: [
      "React Native",
      "TypeScript",
      "Redux",
      "MomentJs",
      "React Native Camera",
      "React Native SVG",
      "Axios",
    ],
    images: [],
    details: "",
    tag: "mobile",
  },
  {
    name: "Clane Mobile App",
    title: "A React Native Consumer Mobile Application",
    tools: [
      "React Native",
      "Redux",
      "MomentJs",
      "React Native Camera",
      "React Native SVG",
      "Axios",
    ],
    images: [],
    details: "",
    tag: "mobile",
  },
  {
    name: "Brij Mobile App",
    title: "A React Native Mobile Application For Storing Asset Documents",
    tools: [
      "React Native",
      "Redux",
      "MomentJs",
      "React Native Camera",
      "React Native SVG",
      "Axios",
    ],
    images: [],
    details: "",
    tag: "mobile",
  },
  {
    name: "Tarvos",
    title: "An E-commerce React Native Mobile Application",
    tools: [
      "React Native",
      "Redux",
      "MomentJs",
      "React Native Camera",
      "React Native SVG",
      "Axios",
    ],
    images: [],
    details: "",
    tag: "mobile",
  },
  {
    name: "Prospa",
    title: "A React Web Application",
    tools: [
      "React Native",
      "Redux",
      "MomentJs",
      "React Native Camera",
      "React Native SVG",
      "Axios",
    ],
    images: [],
    details: "",
    tag: "mobile",
  },
  {
    name: "Rise",
    title: "A React Web Application",
    tools: [
      "React Native",
      "Redux",
      "MomentJs",
      "React Native Camera",
      "React Native SVG",
      "Axios",
    ],
    images: [],
    details: "",
    tag: "mobile",
  },
  {
    name: "Tic Tac Toe",
    title: "A React Web Application",
    tools: [
      "React Native",
      "Redux",
      "MomentJs",
      "React Native Camera",
      "React Native SVG",
      "Axios",
    ],
    images: [],
    details: "",
    tag: "mobile",
  },
];
