backend:
  name: git-gateway
  branch: master

media_folder: "public/images"
public_folder: "/images"
collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Blog Posts" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Author"
        name: "author"
        widget: relation
        required: false
        collection: meta
        file: authors
        searchFields: "authors.*.name"
        displayFields: "authors.*.name"
        valueField: "authors.*.slug"
      - label: "Category"
        name: "category"
        widget: relation
        required: false
        collection: meta
        file: categories
        searchFields: "categories.*.name"
        displayFields: "categories.*.name"
        valueField: "categories.*.slug"
      - label: "Tags"
        name: "tags"
        widget: relation
        required: false
        collection: meta
        file: tags
        searchFields: "tags.*.name"
        displayFields: "tags.*.name"
        valueField: "tags.*.slug"

  - name: "meta"
    label: "Meta"
    folder: "meta"
    create: false
    slug: "{{slug}}"
    files:
      - name: "authors"
        label: "Authors"
        file: "meta/authors.yml"
        description: "Author descriptions"
        fields:
          - name: authors
            label: Authors
            label_singular: "Author"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the author"
              - label: "Name"
                name: "name"
                widget: "string"
                hint: "First and Last"
              - label: "Introduction"
                name: "introduction"
                widget: "text"
      - name: "categories"
        label: "Categories"
        file: "meta/categories.yml"
        description: "List of categories"
        fields:
          - name: categories
            label: Categories
            label_singular: "Category"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the category"
              - label: "Name"
                name: "name"
                widget: "string"
                hint: "category name"
      - name: "tags"
        label: "Tags"
        file: "meta/tags.yml"
        description: "List of tags"
        fields:
          - name: tags
            label: Tags
            label_singular: "Tag"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the tag"
              - label: "Name"
                name: "name"
                widget: "string"
                hint: "tag name"
